version: '3.8'

services:
  wifi-controller:
    build: .
    container_name: wifi-controller
    network_mode: host         # Host ağını kullan
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - .:/app
    environment:
      - SSID=MyAP             # Dilediğiniz SSID ile değiştirin
      - CHANNEL=6             # Dilediğiniz kanalı verin
