version: '3.8'
services:
  ap:
    build: .
    container_name: wifi-ap
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - UPLINK_IFACE=${UPLINK_IFACE:-eth0}
    volumes:
      - ./hostapd.conf:/etc/hostapd/hostapd.conf
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
