version: '3.8'

services:
  wifi-controller:
    build: .
    container_name: wifi-controller
    restart: unless-stopped
    ports:
      - "80:80"
    network_mode: "host"
    privileged: true
    volumes:
      - /etc/netplan:/etc/netplan:ro
      - /var/run/dbus:/var/run/dbus
      - /run/dbus:/run/dbus
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PYTHONUNBUFFERED=1
