version: '3.8'

services:
  wifi-controller:
    build: .
    container_name: wifi-controller
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    volumes:
      - .:/app
      - /etc/network:/etc/network:ro
      - /etc/default/isc-dhcp-relay:/etc/default/isc-dhcp-relay
    environment:
      - DHCP_RELAY_SERVERS=192.168.1.1  # LAN'daki DHCP sunucunuzun IP'si
      - UPLINK_INTERFACE=eth0           # Varsayılan uplink arayüzü
