version: '3.8'

services:
  wifi-controller:
    build: .
    container_name: wifi-controller
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    volumes:
      - ./hostapd.conf.template:/etc/hostapd/hostapd.conf.template
