version: '3.8'

services:
  wifi-controller:
    build: .
    container_name: wifi-controller
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/app
    environment:
      # Uplink arayüzünüzü burada ayarlayın:
      - UPLINK_IFACE=ens192
      # SSID / kanal vs:
      - SSID=MyAP
      - CHANNEL=6
      # İsteğe bağlı: birden fazla SSID isterseniz
      # - GUEST_SSID=GuestAP
      # - GUEST_BRIDGE=br_guest
