version: '3.8'

services:
  wifi-controller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wifi-controller
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    privileged: true
    volumes:
      - .:/app
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - DHCP_RELAY_SERVERS=192.168.1.1
      - UPLINK_INTERFACE=eth0
