version: '3'

services:
  wificontroller:
    build: .
    container_name: wificontroller
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - ./data:/etc/hostapd
