version: "3.8"

services:
  wifi-controller:
    build: .
    image: wifi-controller:latest
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    environment:
      # İsterseniz burada SSID ve CHANNEL tanımı yapabilirsiniz
      SSID: "MyAP"
      CHANNEL: "6"
      # Eğer manuel atamak isterseniz, uplink ve wifi iface:
      # UPLINK_IFACE: "eth0"
      # WIFI_IFACE: "wls160"
