version: '3.8'
services:
  wifi-controller:
    build:
      context: .
      dockerfile: Dockerfile
    # artık host network’e dokunmuyoruz, bridge ve relay'i flag ile tetikleyeceğiz
    ports:
      - "5000:5000"
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - FLASK_ENV=production
      - UPLINK=ens192
      - WIFI_IFACE=wls160
      - BRIDGE=br0
      - START_NETWORK=no   # <-- normalde network setup'u atlıyor
    volumes:
      - /etc/hostapd:/etc/hostapd:ro
