version: '3.8'
services:
  wifi-controller:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - FLASK_ENV=production
      - UPLINK=ens192
      - WIFI_IFACE=wls160
      - BRIDGE=br0
    volumes:
      - /etc/hostapd:/etc/hostapd:ro
