version: '3.8'

services:
  wifi-controller:
    build: .
    network_mode: host     # doğrudan host ağını kullanır
    cap_add: [NET_ADMIN]   
    privileged: true
    volumes:
      - .:/app
    environment:
      - UPLINK_IFACE=ens192
      - DHCP_SERVER=192.168.1.1   # modeminizin DHCP IP’si
      - SSID=MyAP
      - CHANNEL=6
